(module
  (type (;0;) (struct (field i32) (field i32)))
  (type (;1;) (func))
  (type (;2;) (func (param (ref 0))))
  (type (;3;) (struct (field i64) (field i32)))
  (type (;4;) (func))
  (type (;5;) (func (param (ref 3))))
  (table (;0;) 1 funcref)
  (table (;1;) 1 funcref)
  (table (;2;) 1 funcref)
  (table (;3;) 1 funcref)
  (memory (;0;) 0)
  (memory (;1;) 0)
  (memory (;2;) 0)
  (memory (;3;) 0)
  (tag (;0;) (type 1))
  (tag (;1;) (type 1))
  (tag (;2;) (type 4))
  (tag (;3;) (type 4))
  (global (;0;) i32 i32.const 0)
  (global (;1;) i32 i32.const 0)
  (global (;2;) i32 i32.const 0)
  (global (;3;) i32 i32.const 0)
  (export "f0" (func 0))
  (export "f1" (func 1))
  (export "t0" (table 0))
  (export "t1" (table 1))
  (export "g0" (global 0))
  (export "g1" (global 1))
  (export "m0" (memory 0))
  (export "m1" (memory 1))
  (export "tag0" (tag 0))
  (export "tag1" (tag 1))
  (export "func" (func 2))
  (export "f2" (func 3))
  (export "f3" (func 4))
  (export "t2" (table 2))
  (export "t3" (table 3))
  (export "m2" (memory 2))
  (export "m3" (memory 3))
  (export "g2" (global 2))
  (export "g3" (global 3))
  (export "tag2" (tag 2))
  (export "tag3" (tag 3))
  (export "func2" (func 5))
  (elem (;0;) func)
  (elem (;1;) func)
  (elem (;2;) func)
  (elem (;3;) func)
  (func (;0;) (type 1))
  (func (;1;) (type 1))
  (func (;2;) (type 2) (param (ref 0)))
  (func (;3;) (type 4))
  (func (;4;) (type 4))
  (func (;5;) (type 5) (param (ref 3)))
  (data (;0;) "")
  (data (;1;) "")
  (data (;2;) "")
  (data (;3;) "")
)
