(module
  (type $t (;0;) (struct (field $a i32) (field $b i32)))
  (type (;1;) (func))
  (type (;2;) (func (param (ref $t))))
  (type $u (;3;) (struct (field $c i64) (field $d i32)))
  (type (;4;) (func (param (ref $u))))
  (table $table0 (;0;) 1 funcref)
  (table (;1;) 1 funcref)
  (table $table2 (;2;) 1 funcref)
  (table (;3;) 1 funcref)
  (memory $mem0 (;0;) 0)
  (memory (;1;) 0)
  (memory $mem2 (;2;) 0)
  (memory (;3;) 0)
  (tag $tag0 (;0;) (type 1))
  (tag (;1;) (type 1))
  (tag $tag2 (;2;) (type 1))
  (tag (;3;) (type 1))
  (global $glob0 (;0;) i32 i32.const 0)
  (global (;1;) i32 i32.const 0)
  (global $glob2 (;2;) i32 i32.const 0)
  (global (;3;) i32 i32.const 0)
  (export "f0" (func $func0))
  (export "f1" (func 1))
  (export "t0" (table $table0))
  (export "t1" (table 1))
  (export "g0" (global $glob0))
  (export "g1" (global 1))
  (export "m0" (memory $mem0))
  (export "m1" (memory 1))
  (export "tag0" (tag 0))
  (export "tag1" (tag 1))
  (export "func" (func 2))
  (export "f2" (func $func2))
  (export "f3" (func 4))
  (export "t2" (table $table2))
  (export "t3" (table 3))
  (export "m2" (memory $mem2))
  (export "m3" (memory 3))
  (export "g2" (global $glob2))
  (export "g3" (global 3))
  (export "tag2" (tag 2))
  (export "tag3" (tag 3))
  (export "func2" (func 5))
  (elem $elem0 (;0;) func)
  (elem (;1;) func)
  (elem $elem2 (;2;) func)
  (elem (;3;) func)
  (func $func0 (;0;) (type 1))
  (func (;1;) (type 1))
  (func (;2;) (type 2) (param $x (ref $t)))
  (func $func2 (;3;) (type 1))
  (func (;4;) (type 1))
  (func (;5;) (type 4) (param (ref $u)))
  (data $data0 (;0;) "")
  (data (;1;) "")
  (data $data2 (;2;) "")
  (data (;3;) "")
)
